// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Empty
	Person
	Replay
	ListReplay
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Person struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Replay struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *Replay) Reset()                    { *m = Replay{} }
func (m *Replay) String() string            { return proto.CompactTextString(m) }
func (*Replay) ProtoMessage()               {}
func (*Replay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Replay) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListReplay struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *ListReplay) Reset()                    { *m = ListReplay{} }
func (m *ListReplay) String() string            { return proto.CompactTextString(m) }
func (*ListReplay) ProtoMessage()               {}
func (*ListReplay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListReplay) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*Person)(nil), "service.Person")
	proto.RegisterType((*Replay)(nil), "service.Replay")
	proto.RegisterType((*ListReplay)(nil), "service.ListReplay")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyService service

type MyServiceClient interface {
	AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Replay, error)
	ListPeople(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListReplay, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Replay, error) {
	out := new(Replay)
	err := grpc.Invoke(ctx, "/service.myService/AddPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) ListPeople(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListReplay, error) {
	out := new(ListReplay)
	err := grpc.Invoke(ctx, "/service.myService/ListPeople", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyService service

type MyServiceServer interface {
	AddPerson(context.Context, *Person) (*Replay, error)
	ListPeople(context.Context, *Empty) (*ListReplay, error)
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.myService/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).AddPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_ListPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).ListPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.myService/ListPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).ListPeople(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.myService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _MyService_AddPerson_Handler,
		},
		{
			MethodName: "ListPeople",
			Handler:    _MyService_ListPeople_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xd8, 0xb9,
	0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0x64, 0xb8, 0xd8, 0x02, 0x52, 0x8b, 0x8a, 0xf3, 0xf3,
	0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x25, 0x05, 0x2e, 0xb6, 0xa0, 0xd4, 0x82, 0x9c, 0xc4, 0x4a, 0x21, 0x31, 0x2e, 0xb6, 0xe2,
	0x92, 0xc4, 0x92, 0xd2, 0x62, 0xa8, 0x3c, 0x94, 0xa7, 0x64, 0xca, 0xc5, 0xe5, 0x93, 0x59, 0x5c,
	0x02, 0x55, 0xa5, 0xce, 0xc5, 0x56, 0x90, 0x9a, 0x5f, 0x90, 0x03, 0x32, 0x85, 0x59, 0x83, 0xdb,
	0x88, 0x5f, 0x0f, 0x66, 0x3f, 0xc4, 0x92, 0x20, 0xa8, 0xb4, 0x51, 0x21, 0x17, 0x67, 0x6e, 0x65,
	0x30, 0x44, 0x4e, 0x48, 0x9f, 0x8b, 0xd3, 0x31, 0x25, 0x05, 0xea, 0x0c, 0x74, 0x2d, 0x52, 0x08,
	0x01, 0x88, 0x25, 0x4a, 0x0c, 0x42, 0xc6, 0x10, 0x4b, 0x03, 0xc0, 0x66, 0x09, 0xf1, 0xc1, 0x15,
	0x80, 0xbd, 0x24, 0x25, 0x0c, 0xe7, 0x23, 0x5c, 0xa6, 0xc4, 0xe0, 0xc4, 0x19, 0x05, 0xf3, 0x7d,
	0x12, 0x1b, 0x38, 0x34, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0x1f, 0xe1, 0x15, 0x1e,
	0x01, 0x00, 0x00,
}
